### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by donstefan**
i think i just added one more hacker news magazine that is worth reading :+1:

### CODE REVIEW

**Comment by cheeaun** [comment]
Can you put the name of the site as well? Referring to #1 :smile:

**Comment by cheeaun** [comment]
Just wondering, all these news come from https://news.ycombinator.com/ ?

**Comment by donstefan** [comment]
I think i have put the name of the site hmm ? :zap:

**Comment by cheeaun** [comment]
@donstefan yes

**Comment by donstefan** [comment]
@cheeaun i don't know if it's fit perfectly but content is based on research and analyzing :high_brightness:

**Comment by cheeaun** [comment]
Sorry closing this PR, don't think the site is relevant to https://news.ycombinator.com/

**Pull request closed without merging**
